name: screen_corner_radius
description: Screen Corner Radius plugin.
version: 3.0.0
repository: https://github.com/ivangalkindeveloper/screen_corner_radius

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ivangalkindev.screen_corner_radius
        pluginClass: ScreenCornerRadiusPlugin
      ios:
        pluginClass: ScreenCornerRadiusPlugin